#!/bin/ash

set -e

: ${SOCKET:=/var/run/docker.sock}
: ${PORT:=2375}

main() {
    # if the container started with a proper --volume option
    if [ -e $SOCKET ]; then
        # starts a socat proxy from the Docker unix socket to the TCP port
        exec socat -d -d TCP-LISTEN:${PORT},fork UNIX:${SOCKET}
    else
        # otherwise prints the correct command to stdout
        cat << EOF
        docker run -d \
            -p $PORT:$PORT \
            --volume=$SOCKET:$SOCKET \
            --name=docker-http-proxy \
            gcbartlett/docker-http-proxy
EOF
        exit 1
    fi
}

main "$@"
